name: Ship preview builds on merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          cache: yarn

      - run: |
          yarn install
          yarn workspaces run vscode:prepublish

      - uses: orta/monorepo-deploy-nightly@master
        env:
          VSCE_TOKEN: ${{ secrets.AZURE_PAN_TOKEN }}
        with:
          vsce-params: "--pre-release"
